### ISSUE TITLE
updating the onLabel text repeatedly?

### ISSUE THREAD

**Issue by kajensen** [bvogelzang/SevenSwitch#27]
I'm having some trouble updating the onLabel, accessing it via [sevenSwitch.onLabel setText:]. The problem is, the text is updated seemingly at random points ~every 60+ seconds, when I want it to be much faster than that (~10 seconds or faster). I'm using the main queue and setting [sevenSwitch.onLabel setNeedsDisplay] after I update the label. How could I go about fixing this?

**Comment by bvogelzang** [comment]
I did a few tests and I was able to get the `onLabel` updating successfully at a set interval using a timer. You shouldn't need to call `setNeedsDisplay` to see a change on the label since a call to `setText` should be sufficient. 

I can't really offer much help unless you provide me with some code or provide more detail. It sounds to me that your issue is elsewhere in your code and is not an issue with `SevenSwitch`.
