### ISSUE TITLE
CocoaPods Issue

### ISSUE THREAD

**Issue by Bierrot** [bvogelzang/SevenSwitch#28]
When I add " pod 'SevenSwitch', '~> 2.0' " to my Podfile and try to install, I got this error : 

[!] Unable to satisfy the following requirements:
- `SevenSwitch (~> 2.0)` required by `Podfile`

CocoaPods website only find SevenSwitch1.4.0.

Thanks.

**Comment by jimijon** [comment]
Same here.

**Comment by lucasgerard** [comment]
Same, thanks

**Comment by bvogelzang** [comment]
`SevenSwitch 2.0.0` has been submitted to CocoaPods. Keep in mind you'll have to update CocoaPods to the pre-release version (0.36.0.rc.1) in order to properly use `SevenSwitch` since Swift support has not been officially released yet. This was part of the reason for the delay.

To update to pre-release: `[sudo] gem install cocoapods --pre`

More information can be found at: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
